server:
  port: 9001

spring:
  application:
    name: TOURIST

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/
  instance:
    hostname: localhost